### ISSUE TITLE
DID Comm messaging section

### ISSUE THREAD

**Issue by PaddyMc** [elesto-dao/elesto#124]
The did comm messaging section of the issuer dashboard contains the functionality to send DIDComm Messages between issuers.

This task is for the full messaging round trip between two issuers including the webhook querier ( if needed ).

This task is complicated and needs some investigation.

Areas to note:

- Can messages be queried from the agent?
- How will the webui receive updates?
  - Is a webhook needed to update the webui?

Wireframe:
https://whimsical.com/elesto-issuer-dashboard-QwJvnvs7WERcUauDREkLoM

Design:
![Selection_109.png](https://images.zenhubusercontent.com/602a87053c2bdd867c19ecc6/69d9977a-f252-46ef-8c9a-1be0fb1310cd)

![Selection_108.png](https://images.zenhubusercontent.com/602a87053c2bdd867c19ecc6/d0160fa8-32fe-4f93-a88f-e2a8233259d7)

**Comment by noandrea** [comment]
see the project specific issues elesto-issuer-dasboard#7
