### ISSUE TITLE
CompactJSON return should be []byte instead string

### ISSUE THREAD

**Issue by hpsing** [elesto-dao/elesto#134]
*Issue*

https://github.com/elesto-dao/elesto/blob/9c57d8c395f049220b8f96cbc0f81064efdb8bed/x/credential/credential.go#L33-L37

CompactJSON should return a []byte instead string

*fix*

1. Change return type in [helpers.go](https://github.com/elesto-dao/elesto/blob/9c57d8c395f049220b8f96cbc0f81064efdb8bed/x/credential/helpers.go#L16)
2. Type Fix in [msg_validation.go](https://github.com/elesto-dao/elesto/blob/9c57d8c395f049220b8f96cbc0f81064efdb8bed/x/credential/msg_validation.go#L26)
3. Type Fix in [msg_server.go](https://github.com/elesto-dao/elesto/blob/9c57d8c395f049220b8f96cbc0f81064efdb8bed/x/credential/keeper/msg_server.go#L101)

**Comment by noandrea** [comment]
yes, it is addressed in https://github.com/elesto-dao/elesto/pull/120
