### ISSUE TITLE
Protect release branches 

### ISSUE THREAD

**Issue by noandrea** [elesto-dao/elesto#177]
The branches with pattern `release/*` should be protected so they cannot be deleted by mistake 

### Proposed solution
Use Terraform to automatically configure the protection branch + settings for the "elesto" repository.
It could be easily added to other repositories later on.

**Comment by artemijspavlovs** [comment]
I have the Terraform code ready for this. 
@glebiller @alain2sf how should we handle this governance? 

**How about:** we create a generic template with GitHub groups, protection policies and other settings, store it in the infra code base with a list of repos we manage and run the Terraform against all the repositories on daily basis via github action?

**Comment by glebiller** [comment]
@artemijspavlovs Totally, I think we should also include some generic Github Action workflows.
I think we can use [issue 51 in elesto home](https://github.com/elesto-dao/home/issues/51) to start the template.

**Comment by artemijspavlovs** [comment]
I'll put together the entire template then and create a PR with everything included instead of adding 1 line of terraform for each point as part of this issue.

@glebiller @noandrea does that sound reasonable?
