### ISSUE TITLE
Support pre-registration of did in genesis

### ISSUE THREAD

**Issue by noandrea** [elesto-dao/elesto#203]
Allow pre-registering of did in genesis, to avoid squatting later on.

This is meaningful mostly for vanity did. 

A question can be raised about if we want to allow vanity dids. In case we do not, then we should prevent the creation of did that are not UUID format. 

It is a possibility to enable, at a later stage, vanity did auctions.

**Comment by Bartkeeper** [comment]
Working Document is here: https://www.notion.so/allinbits/Vanity-DIDs-22ab8bd2e9454a729c97d18eccacb34f
