### ISSUE TITLE
build: Elesto networks

### ISSUE THREAD

**Issue by dbg-dev** [elesto-dao/elesto#75]
## Aim

This epic describes the network requirements for Elesto

## Network

Initial requirements suggest the following:

- elesto-testnet-1 (2+ validators)
  - get in touch with Infrasec for deployment and stuff
- elesto-canary-1 (incentivized)  (what for?)

Also need to consider: network monitoring => Prometheus & Grafana

Note: - elesto-mainnet-1 is issue #76

**Comment by glebiller** [comment]
@SenorMonito What is the difference between testnet & canary? 
Is one public & the other one private?
