### ISSUE TITLE
docs: Validator documentation

### ISSUE THREAD

**Issue by dbg-dev** [elesto-dao/elesto#77]
## Aim

The purpose of this issue is to document

## Scope 

- Machine specifications
- Setup instructions 
- non-Kubernetes set-up validators ⇒ throw away server setup

## Definition of Done

- Target = Be able to bring up a team testnet (5-6 nodes) by end of the sprint

## Resources

- Archway and Osmosis documentation is very good

**Comment by noandrea** [comment]
- Archway: https://docs.archway.io/docs/node/install/
- Osmosis: https://docs.osmosis.zone/developing/network/join-mainnet.html
