### ISSUE TITLE
design: token distribution

### ISSUE THREAD

**Issue by dbg-dev** [elesto-dao/elesto#79]
initial allocation of the 200m tokens

 - [ ] document on notion

**Comment by noandrea** [comment]
need clarification

**Comment by PaddyMc** [comment]
https://www.notion.so/allinbits/Validators-for-ClearTrie-6b175150c89a4503ab1f11dae9b6de97#2fbf47045d764b4ebce94e5d73366819

**Comment by PaddyMc** [comment]
![meta-chart (2).jpeg](https://images.zenhubusercontent.com/602a87053c2bdd867c19ecc6/ce95d993-d9c8-4023-b492-de0d36339205)

**Comment by noandrea** [comment]
in review by Shuyi

**Comment by noandrea** [comment]
completed.
