### ISSUE TITLE
Import/Export simulation fails

### ISSUE THREAD

**Issue by noandrea** [elesto-dao/elesto#83]
We have an error in the simulation for the import/export of the state, here are some details:

the issue seems somewhat related to these two (fairly old) issues in the cosmos-SDK:
- https://github.com/cosmos/cosmos-sdk/issues/4383
- https://github.com/cosmos/cosmos-sdk/issues/4367

when we run the TestAppSimulationAfterImport the result is panic:
```
panic: calculated final stake for delegator elesto1qytdwn45zw6rjrstm6zzjvl2x2ck9jfq0yygtv greater than current stake
final stake:	469303483982.000000000000000000
current stake:	424203504734.191994867366789693 [recovered]
```

the code is here: https://github.com/elesto-dao/elesto/blob/main/app/simulation_test.go

a note is when we run a single simulation setting the seed to `100_000_000_000` the simulation ends successfully

**Comment by gsora** [comment]
#123 should address the issue.
